apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- deployment.yaml
- service.yaml

namespace: instavote

images:
  - name: schoolofdevops/vote
    newTag: v3

replicas:
  - name: vote
    count: 1

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "sre@example.com"

configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=FluxCD
      - OPTION_B=ArgoCD
